//! Compile-time defaults for every palette-eligible `Action`.
//!
//! `name` is auto-generated by `Action::snake_name()` at runtime —
//! only `description` and `key_hint` need to be listed here.

use crate::keybind::bindings::Action;

pub fn palette_defaults() -> &'static [(Action, &'static str, &'static str)] {
    &[
        // ── File / buffer ──────────────────────────────────────
        (Action::Save, "Save current buffer", ":w"),
        (Action::SaveAs, "Save as…", ":w <path>"),
        (Action::Quit, "Quit (check modified)", ":q"),
        (Action::ForceQuit, "Force quit", ":q!"),
        (Action::QuitAll, "Quit all buffers", ":qa"),
        (Action::ForceQuitAll, "Force quit all", ":qa!"),
        (Action::BufferNext, "Next buffer", ":bn"),
        (Action::BufferPrev, "Previous buffer", ":bp"),
        (Action::BufferList, "List buffers", ":ls"),
        (Action::BufferClose, "Close current buffer", ":bd"),
        (Action::FilePicker, "Open file picker", ":ff"),
        (Action::Mru, "Recent files", "space r"),
        (Action::BookMarks, "Show marks", "marks"),
        // ── Navigation ─────────────────────────────────────────
        (Action::MoveLeft, "Move cursor left", "h"),
        (Action::MoveRight, "Move cursor right", "l"),
        (Action::MoveUp, "Move cursor up", "k"),
        (Action::MoveDown, "Move cursor down", "j"),
        (Action::MoveWordForward, "Move word forward", "w"),
        (Action::MoveWordBackward, "Move word backward", "b"),
        (Action::MoveLineStart, "Go to line start", "0"),
        (Action::MoveLineEnd, "Go to line end", "$"),
        (Action::MoveToFirstLine, "Go to first line", "gg"),
        (Action::MoveToLastLine, "Go to last line", "G"),
        (Action::PageUp, "Page up", "PageUp"),
        (Action::PageDown, "Page down", "PageDown"),
        (Action::ScrollCenter, "Center cursor on screen", "zz"),
        // ── Editing ────────────────────────────────────────────
        (Action::Backspace, "Delete char left", "Backspace"),
        (Action::DeleteCharForward, "Delete char right", "x"),
        (Action::DeleteCurrentLine, "Delete current line", "dd"),
        (Action::DeleteToEndOfLine, "Delete to end of line", "d$"),
        (Action::InsertNewline, "Insert newline", "Enter"),
        (Action::InsertNewlineBelow, "Insert line below", "o"),
        (Action::InsertNewlineAbove, "Insert line above", "O"),
        (Action::Undo, "Undo", "u"),
        (Action::IndentLine, "Indent line", ">"),
        (Action::OutdentLine, "Outdent line", "<"),
        (Action::Paste, "Paste from register", "p"),
        // ── Clipboard ──────────────────────────────────────────
        (Action::YankCurrentLine, "Yank line", "yy"),
        (Action::YankCurrentWord, "Yank word", "yw"),
        (
            Action::YankToSystemClipboard,
            "Yank to system clipboard",
            "\"+y",
        ),
        (
            Action::PasteFromSystemClipboard,
            "Paste from system clipboard",
            "\"+p",
        ),
        (
            Action::CutToSystemClipboard,
            "Cut to system clipboard",
            "\"+d",
        ),
        // ── Modes ──────────────────────────────────────────────
        (Action::EnterInsert, "Enter insert mode", "i"),
        (Action::EnterAppend, "Enter append mode", "a"),
        (Action::EnterBrief, "Enter brief mode", "gi"),
        (Action::EnterCommand, "Enter command mode", ":"),
        (Action::ExitMode, "Exit to normal mode", "Esc"),
        // ── Visual ─────────────────────────────────────────────
        (Action::EnterVisual, "Enter visual mode", "v"),
        (Action::EnterVisualLine, "Enter visual line mode", "V"),
        (
            Action::EnterVisualBlock,
            "Enter visual block mode",
            "Ctrl+v",
        ),
        // ── Windows ────────────────────────────────────────────
        (Action::SplitHorizontal, "Split horizontally", "Ctrl+w s"),
        (Action::SplitVertical, "Split vertically", "Ctrl+w v"),
        (Action::CloseWindow, "Close window", "Ctrl+w q"),
        (Action::OnlyWindow, "Only current window", "Ctrl+w o"),
        (Action::FocusNextWindow, "Focus next window", "Ctrl+w w"),
        (Action::FocusPrevWindow, "Focus previous window", "Ctrl+w W"),
        // ── Gutter toggles ────────────────────────────────────
        (
            Action::ToggleLineNumbers,
            "Toggle line numbers",
            "space t n",
        ),
        (
            Action::ToggleRelativeLineNumbers,
            "Toggle relative line numbers",
            "space t r",
        ),
        (Action::ToggleGitGutter, "Toggle git gutter", "space t g"),
        (
            Action::ToggleBookmarks,
            "Toggle bookmarks display",
            "space t b",
        ),
        (
            Action::ToggleBookmarkAtCursor,
            "Set/remove bookmark",
            "space m",
        ),
        // ── Search ─────────────────────────────────────────────
        (Action::EnterSearch, "Enter search mode", "/"),
        (Action::SearchNext, "Search next", "n"),
        (Action::SearchPrev, "Search previous", "N"),
        (Action::SearchCurrentWord, "Search current word", "*"),
        (
            Action::ClearSearchHighlight,
            "Clear search highlight",
            ":noh",
        ),
        // ── Git ────────────────────────────────────────────────
        (Action::GitStatus, "Git status", ":gs"),
        (Action::GitLog, "Git log", ":glog"),
        (Action::HunkNext, "Next git hunk", "space h n"),
        (Action::HunkPrev, "Previous git hunk", "space h p"),
        (Action::GitRevert, "Revert hunk", "space g r"),
        (Action::HunkPopup, "Show hunk diff", "space h d"),
        // ── Other ──────────────────────────────────────────────
        (Action::FunctionList, "Function list", "space f"),
        (Action::LastRg, "Last ripgrep", ":lastrg"),
        (Action::RgUnderCursor, "Ripgrep under cursor", "space r g"),
        (Action::TogglePopup, "Toggle which-key popup", "space t t"),
        (Action::RepeatLastChange, "Repeat last change", "."),
    ]
}
